# Generated by Django 2.2.3 on 2019-07-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_auto_20190709_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film_schedule',
            name='film',
        ),
        migrations.RemoveField(
            model_name='film_schedule',
            name='hall',
        ),
        migrations.AddField(
            model_name='film_schedule',
            name='film_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film_schedule',
            name='hall_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
