# Generated by Django 2.2.3 on 2019-07-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
