# Generated by Django 2.2.3 on 2019-07-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cinema', '0007_delete_booking'),
    ]

    def insertData(apps, schema_editor):
        Hall = apps.get_model('cinema', 'Hall')
        user = Hall(name='Moscow', length=7, width=20)
        user.save()
        user = Hall(name='London', length=4, width=10)
        user.save()


    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('schedule_id', models.IntegerField()),
                ('place_id', models.CharField(max_length=10)),
                ('status', models.CharField(default='CREATED', max_length=10)),
            ],
            options={
                'index_together': {('schedule_id', 'place_id', 'status')},
            },
        ),
        migrations.RunPython(insertData),
    ]
