# Generated by Django 2.2.3 on 2019-07-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cinema', '0009_set_hall'),
    ]

    def insertData(apps, schema_editor):
        User = apps.get_model('cinema', 'User')
        user = User(password='_Qwerty123', email='admin@cinema.io', user_name='admin', user_role='admin')
        user.save()
        user = User(password='12345', email='test@cinema.io', user_name='test', user_role='user')
        user.save()


    operations = [
        migrations.RunPython(insertData),
    ]
